import { Metadata } from 'next';
import { propagateServerField } from 'next/dist/server/lib/render-server';

// page.tsxではなくlayout.tsxのオブジェクト形式で指定するには型指定がいる(importも必要)
export const metadata: Metadata = {
  // title: 'Next.js',
  title: {
    absolute: '',
    // 決まったキーワードでpage.tsxに明示的にメタデータがない時に各ページに反映させるテンプレートのようなもの
    default: 'デフォルトです',
    // 各ページでキーワードの微調整をするためのもの
    template: '%sです',
  },
  description: 'Generated by Next.js',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <header>
          <p>ヘッダーです</p>
        </header>
        {children}
        <footer>
          <p>フッターです</p>
        </footer>
      </body>
    </html>
  );
}
