import { propagateServerField } from 'next/dist/server/lib/render-server';

// layoutには最初からmetadataが作られているが重複するとpage.tsxの内容が優先される
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <header>
          <p>ヘッダーです</p>
        </header>
        {children}
        <footer>
          <p>フッターです</p>
        </footer>
      </body>
    </html>
  );
}
